...FE.........F..............
======================================================================
ERROR: testMem (__main__.MemTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/root/test/EgressTestV2.py", line 162, in testMem
    self.assertEqual(int(Sendcmd("more /home/root/test/mem/mem*.txt | grep -c ': ok'")),7)
TypeError: int() argument must be a string or a number, not 'NoneType'

======================================================================
FAIL: testRWSpeed (__main__.EEMCTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/root/test/EgressTestV2.py", line 64, in testRWSpeed
    self.assertGreater(float(Sendcmd("hdparm -t /dev/mmcblk0 | awk '{printf $11}'")),16)
AssertionError: 15.73 not greater than 16

======================================================================
FAIL: testRWspeed (__main__.SDCardTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/root/test/EgressTestV2.py", line 91, in testRWspeed
    self.assertGreaterEqual(float(Sendcmd("hdparm -t /dev/mmcblk1 | awk '{printf $11}'")),68)
AssertionError: 64.950000000000003 not greater than or equal to 68

----------------------------------------------------------------------
Ran 29 tests in 39.711s

FAILED (failures=2, errors=1)
